### ISSUE TITLE
The module of meep_ext is not found in the scripts

### ISSUE THREAD

**Issue by yiditudou** [johnaparker/miepy#1]
i try to install the module of meep_ext but not exist, could you tell me where it is? thank you

**Comment by johnaparker** [comment]
**note:** This applies to running the code examples in https://github.com/johnaparker/miepy/tree/master/examples/fdtd_compare

In addition to installing `meep` and `numpipe`, `meep_ext` can be installed from source here:
https://github.com/johnaparker/meep_ext
