### ISSUE TITLE
Fail to install miepy!!!

### ISSUE THREAD

**Issue by tuyen-le** [johnaparker/miepy#11]
Dear authors,

Please help to check whether we can install miepy normally?

I tried to type

pip install miepy

but it took me so long for waiting...(more than one day) without any progess.

I used Spyder on the environment of Anaconda Navigator. 

Thank you!
Student
Le

**Comment by tuyen-le** [comment]
I also create environment and active miepy:

conda create --name miepy python=3

conda active miepy 

then follow your instruction to do:

conda install -c japarker miepy

-> error: the package "japarker" is not available from current channels: - miepy


What should I do now to fix this problem?

Thank you,
Student,
Le

**Comment by johnaparker** [comment]
There's something not working with the current install, but I just verified that the following commands issued in a fresh Anaconda environment correctly installs MiePy:
```
conda install -c conda-forge quaternion
conda install -c moble spherical_functions
pip install miepy
```
It shouldn't be taking days -- perhaps the Anaconda environment is faulty.

**Comment by tuyen-le** [comment]
Dear Mr. Parker,

I successfully install miepy in Linux operating system. But I got a new problem of "numpipe module" when running the code "cube_scattering.py" as follow:

------------------------------------------------------

  File "/home/yuri/Desktop/miepy-master/examples/fdtd_compare/cube_scattering.py", line 9, in <module>
    from numpipe import scheduler, pbar

  File "/home/yuri/anaconda3/lib/python3.8/site-packages/numpipe/__init__.py", line 12, in <module>
    from . import parser

  File "/home/yuri/anaconda3/lib/python3.8/site-packages/numpipe/parser.py", line 7, in <module>
    notifications_default_delay = config.get_config()['notifications']['delay_default']

  File "/home/yuri/anaconda3/lib/python3.8/site-packages/numpipe/config.py", line 12, in get_config
    config = toml.load(path)

  File "/home/yuri/anaconda3/lib/python3.8/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:

FileNotFoundError: [Errno 2] No such file or directory: '/home/yuri/.config/numpipe/numpipe.conf'
-------------------------------------------------------------------------

I could not find the "numpipe.conf" in specified folder.

Do you have any solution for this issue?

Thank you very much!

Student,
Le

**Comment by johnaparker** [comment]
I see, this script depends on my other package, numpipe, and there is a bug when installing it by Python wheels (https://github.com/johnaparker/numpipe/issues/1). You can manually create the file `numpipe.conf` at the location it mentions (create .config/numpipe directory if it doesn't exist). Then place the following contents in it:

```
[execution]
    parallel_default = true

[notifications]
    delay_default = 120

    [notifications.telegram]
    token = ""
    chat_id = 0

[progress]
    character = "#"
    mininterval = 0.1
```

**Comment by tuyen-le** [comment]
Dear Mr. Parker,

I will try it. Thank you very much!

Student,
Le
